# This is a basic workflow to help you get started with Actions

name: build_main

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Concat main.csv
        run: |
          ./gradlew run
        env:
          TOKEN: "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"
          REPOS: "spectrum-data/conf2022_the_best_in_the_tests_templates_kotlin"
          LOCAL_FILE_NAME: "local.csv"
          CONCATED_FILE_NAME: "main.csv"
          MAIN_HEADER: "author|number|stringToProcessed|isDisabled|commentOnFailure|publishTime"
          DELIMITER: "|"

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Build main.csv'
