# This is a basic workflow to help you get started with Actions

name: build_main

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: is gh api working?
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/spectrum-data/conf2022_the_best_in_the_tests_templates_kotlin/forks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Concat main.csv
        run: |
          ./gradlew run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS: "spectrum-data/conf2022_the_best_in_the_tests_templates_kotlin;Lokbugs/test_forking_private"
          LOCAL_FILE_NAME: "local.csv"
          CONCATED_FILE_NAME: "main.csv"
          
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: Lokbugs
          message: 'Build main.csv'
