# This is a basic workflow to help you get started with Actions

name: build_main

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: gh auth
        run:
          gh auth login
      
      - name: Concat main.csv
        run: |
          was_header_added=false
          declare -a repos=("spectrum-data/conf2022_the_best_in_the_tests_templates_kotlin")

          for repo in "${repos[@]}";
          do
            echo "current repo is: $repo"

            forks_json=$(gh api --header 'Accept: application/vnd.github.v3+json' --method GET /repos/$repo/forks)

            for fork_json in $(echo "$forks_json" | jq -c '.[]'); 
            do	
              fork_url=$(echo $fork_json | jq '. | .html_url')

              owner=$(echo $fork_json | jq '. | .owner.login')
              owner="${owner%\"}"
              owner="${owner#\"}"

              fork_repo_name=$(echo $fork_json | jq '. | .name')
              fork_repo_name="${fork_repo_name%\"}"
              fork_repo_name="${fork_repo_name#\"}"

              url="${fork_url%\"}"
              url="${url#\"}"
              url=$(echo $url | cut -c 9-)

              git clone https://$GH_TOKEN@$url -b 'main'

              if test -f "$PWD/$fork_repo_name/$LOCAL_FILE_NAME"; then
                if ! $was_header_added ; then 
                  cat "$PWD/$fork_repo_name/$LOCAL_FILE_NAME" > "$CONCATED_FILE_NAME"
                  was_header_added=true
                else
                  tail -n +2 "$PWD/$fork_repo_name/$LOCAL_FILE_NAME" >> "$CONCATED_FILE_NAME"
                fi


                if test -d "$PWD/$owner/"; then
                  rm -rf "$PWD/$owner/"
                fi

                mkdir $owner
                cp "$PWD/$fork_repo_name/$LOCAL_FILE_NAME" "$PWD/$owner/$LOCAL_FILE_NAME"
              fi

              rm -rf $fork_repo_name
            done
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCAL_FILE_NAME: "local.csv"
          CONCATED_FILE_NAME: "main.csv"
          
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: Lokbugs
          message: 'Build main.csv'
