# This is a basic workflow to help you get started with Actions

name: build_main

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Concat main.csv
        run: |
          ./gradlew run
        env:
          TOKEN: "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"
          REPOS: "spectrum-data/conf2022_the_best_in_the_tests_templates_kotlin"
          LOCAL_FILE_NAME: "local.csv"
          MAIN_FILE_NAME: "main.csv"
          MAIN_HEADER: "author|number|stringToProcessed|isDisabled|commentOnFailure|publishTime"
          DELIMITER: "|"
          MODE: "concat"
          TELEGRAM_TOKEN: "5732312328:AAGr0XD9U_nCt1M5qOFTZlH7sOKLyfw1kfM"
          TELEGRAM_CHAT_IDS: "472695058;392472524"

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Build main.csv'
